import localFont from "next/font/local";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

const customFont1 = localFont({
  src: "./fonts/Catamaran-Black.ttf",
  variable: "--catamaran-font"
});

const customFont2 = localFont({
  src: "./fonts/Raleway-Regular.ttf",
  variable: "--raleway-font"
});

export const metadata = {
  title: "Cinema",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${customFont1.variable} ${customFont2.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
